const BuiltinRoles = {
  USER: {
    name: "user",
    permissions: [
      "user:create:self",
      "user:read:self",
      "user:update:self",
      "user:update.email:none",
      "user:update.password:self",
      "user:delete:self",
      "role:create:none",
      "role:read:self.list_item",
      "role:update:none",
      "role:delete:none",
      "property:create:self",
      "property:read:public",
      "property:update:self",
      "property:delete:self",
      "lessee:create:self",
      "lessee:read:self",
      "lessee:update:self",
      "lessee:delete:self",
      "contract:create:self",
      "contract:read:self",
      "contract:update:self",
      "contract:delete:self",
    ]
  },
  AGENT: {
    name: "agent",
    permissions: [
      "user:create:self",
      "user:read:account.lean",
      "user:update:self",
      "user:update.email:self",
      "user:update.password:self",
      "user:delete:self",
      "role:create:none",
      "role:read:none",
      "role:update:none",
      "role:delete:none",
      "property:create:account",
      "property:read:account",
      "property:update:account",
      "property:delete:account",
      "lessee:create:account",
      "lessee:read:account",
      "lessee:update:account",
      "lessee:delete:account",
      "contract:create:account",
      "contract:read:account",
      "contract:update:account",
      "contract:delete:account",
    ]
  },
  MANAGER: {
    name: "manager",
    permissions: [
      "user:create:self",
      "user:read:client.lean",
      "user:update:self",
      "user:update.email:self",
      "user:update.password:self",
      "user:delete:self",
      "role:create:none",
      "role:read:all.list_item",
      "role:update:none",
      "role:delete:none",
      "property:create:client",
      "property:read:client",
      "property:update:client",
      "property:delete:client",
      "lessee:create:client",
      "lessee:read:client",
      "lessee:update:client",
      "lessee:delete:client",
      "contract:create:client",
      "contract:read:client",
      "contract:update:client",
      "contract:delete:client",
    ]
  },
  ADMIN: {
    name: "admin",
    permissions: [
      "user:create:all",
      "user:read:all",
      "user:update:all",
      "user:update.email:all",
      "user:update.password:all",
      "user:delete:all",
      "role:create:all",
      "role:read:all",
      "role:update:all",
      "role:delete:all",
      "property:create:all",
      "property:read:all",
      "property:update:all",
      "property:delete:all",
      "lessee:create:all",
      "lessee:read:all",
      "lessee:update:all",
      "lessee:delete:all",
      "contract:create:all",
      "contract:read:all",
      "contract:update:all",
      "contract:delete:all",
    ]
  }
}

export default BuiltinRoles;
